### ISSUE TITLE
Unable to read from network shares

### ISSUE THREAD

**Issue by Holmes70** [integrated-application-development/delphilint#17] opened 2024-03-21 13:42 UTC
### Prerequisites

- [X] This bug is in DelphiLint, not SonarDelphi, SonarQube, or my Delphi code.
- [X] This bug has not already been reported.

### Delphi IDE version

12

### DelphiLint version

1.0.1

### SonarDelphi version

1.3.0

### Issue description

When analyzing a project on a network share or more specifically on a Parallels share from a Windows VM on a Mac. The system fails with the following error message:
[Window Title]
Warnung

[Main Instruction]
DelphiLint encountered a problem during analysis.

[Content]
An error was raised (au.com.integradev.delphi.file.DelphiFile$DelphiFileConstructionException: Failed to construct DelphiFile (C:\Home\Documents\Embarcadero\Studio\Projekte\Unit41.pas (Das System kann den angegebenen Pfad nicht finden))
).

[OK]

The files are in fact located at \\Mac\Home\Documents\Embarcadero\Studio\Projekte. 

### Steps to reproduce

Try analyzing a file on a network share via UNC path.

**Comment by fourls** [comment] 2024-03-21 23:21
Hi, thanks for raising this issue. I've reproduced and am looking into the cause now. 

As a short-term workaround, you can [map a network drive](https://support.microsoft.com/en-au/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d) to your UNC path. According to the [Parallels docs](https://kb.parallels.com/en/116127) this should work fine within your VM.

**Comment by fourls** [comment] 2024-03-22 01:53
This turned out to be an upstream bug with SonarDelphi - I've raised integrated-application-development/sonar-delphi#208 to fix it.

Once a new SonarDelphi release comes out containing this fix:
- Changing DelphiLint's SonarDelphi version (in Settings) to the new version should resolve your UNC path troubles.
- The next DelphiLint release will default to the new version.
- I'll close this issue.

**Comment by fourls** [comment] 2024-04-02 06:36
[SonarDelphi 1.4.0](https://github.com/integrated-application-development/sonar-delphi/releases/tag/v1.4.0) is now out containing a fix to this issue.

To resolve this issue, you can either:

- Keep using your current DelphiLint version and change DelphiLint's SonarDelphi version (in Settings) to 1.4.0.
- Update to [DelphiLint 1.0.2](https://github.com/integrated-application-development/delphilint/releases/tag/v1.0.2), which defaults to SonarDelphi 1.4.0.

**Closed by fourls** 2024-04-02 06:36 UTC
Labels: bug
